"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { getProfile } from "@/lib/auth/getProfile";
import { rateLimit } from "@/lib/rateLimit";

const RATE_MAX = 10;
const RATE_WINDOW = 60_000; // 1 min

interface ActionResult {
  success: boolean;
  error?: string;
}

// ---------------------------------------------------------------------------
// Add car unit
// ---------------------------------------------------------------------------

export async function addCarUnit(formData: FormData): Promise<ActionResult> {
  const profile = await getProfile();
  if (!profile || profile.role !== "BUSINESS" || !profile.business_id) {
    return { success: false, error: "Unauthorized" };
  }

  const rl = rateLimit(`${profile.id}:biz_car`, RATE_MAX, RATE_WINDOW);
  if (!rl.ok) return { success: false, error: "Too many requests. Slow down." };

  const carModelId = (formData.get("car_model_id") as string)?.trim();
  const displayName = (formData.get("display_name") as string)?.trim() || null;
  const color = (formData.get("color") as string)?.trim() || null;
  const colorHex = (formData.get("color_hex") as string)?.trim() || null;
  const creditsRaw = formData.get("credits_per_hour") as string;
  const creditsPerHour = creditsRaw ? parseInt(creditsRaw, 10) : null;

  if (!carModelId) {
    return { success: false, error: "A car model must be selected." };
  }
  if (creditsPerHour !== null && (!Number.isFinite(creditsPerHour) || creditsPerHour < 1)) {
    return { success: false, error: "Credits/hour must be a positive number." };
  }

  const supabase = await createClient();
  // VIN and license_plate are auto-generated by DB defaults
  const { error } = await supabase.from("car_units").insert({
    business_id: profile.business_id,
    car_model_id: carModelId,
    display_name: displayName,
    color,
    color_hex: colorHex,
    credits_per_hour: creditsPerHour,
  });

  if (error) return { success: false, error: error.message };

  revalidatePath("/biz/cars");
  return { success: true };
}

// ---------------------------------------------------------------------------
// Update car unit
// ---------------------------------------------------------------------------

export async function updateCarUnit(formData: FormData): Promise<ActionResult> {
  const profile = await getProfile();
  if (!profile || profile.role !== "BUSINESS") {
    return { success: false, error: "Unauthorized" };
  }

  const rl = rateLimit(`${profile.id}:biz_car`, RATE_MAX, RATE_WINDOW);
  if (!rl.ok) return { success: false, error: "Too many requests. Slow down." };

  const id = formData.get("id") as string;
  const displayName = (formData.get("display_name") as string)?.trim() || null;
  const color = (formData.get("color") as string)?.trim() || null;
  const colorHex = (formData.get("color_hex") as string)?.trim() || null;
  const creditsRaw = formData.get("credits_per_hour") as string;
  const creditsPerHour = creditsRaw ? parseInt(creditsRaw, 10) : null;

  if (!id) return { success: false, error: "Missing unit id." };
  if (creditsPerHour !== null && (!Number.isFinite(creditsPerHour) || creditsPerHour < 1)) {
    return { success: false, error: "Credits/hour must be a positive number." };
  }

  // RLS ensures only own units are updatable
  const supabase = await createClient();
  const { error } = await supabase
    .from("car_units")
    .update({ display_name: displayName, color, color_hex: colorHex, credits_per_hour: creditsPerHour })
    .eq("id", id);

  if (error) return { success: false, error: error.message };

  revalidatePath("/biz/cars");
  return { success: true };
}

// ---------------------------------------------------------------------------
// Toggle active / inactive
// ---------------------------------------------------------------------------

export async function toggleUnitActive(unitId: string, active: boolean): Promise<ActionResult> {
  const profile = await getProfile();
  if (!profile || profile.role !== "BUSINESS") {
    return { success: false, error: "Unauthorized" };
  }

  const supabase = await createClient();
  const { error } = await supabase
    .from("car_units")
    .update({ active })
    .eq("id", unitId);

  if (error) return { success: false, error: error.message };

  revalidatePath("/biz/cars");
  return { success: true };
}

// ---------------------------------------------------------------------------
// Delete car unit
// ---------------------------------------------------------------------------

export async function deleteCarUnit(unitId: string): Promise<ActionResult> {
  const profile = await getProfile();
  if (!profile || profile.role !== "BUSINESS") {
    return { success: false, error: "Unauthorized" };
  }

  const supabase = await createClient();
  const { error } = await supabase.from("car_units").delete().eq("id", unitId);

  if (error) return { success: false, error: error.message };

  revalidatePath("/biz/cars");
  return { success: true };
}
